services:
  triage-app:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      AI_SERVICE_URL: http://ai:8001
      WATCHFILES_FORCE_POLLING: "true"
      GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET}
    volumes:
      - ./app:/app

  ai:
    build: ./ai-service
    ports:
      - "8001:8001"
    environment:
      WATCHFILES_FORCE_POLLING: "true"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPEN_AI_MODEL: ${OPEN_AI_MODEL}
    volumes:
      - ./ai-service:/ai-service